[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
auto_detect_remappings = true

[dependencies]
forge-std = { version = "1.9.1" }
"@openzeppelin-contracts" = { version = "5.0.2" }
"@openzeppelin-contracts-upgradeable" = { version = "5.0.2" }

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
