name: "Marketplace Backend"
mode: "debug"
port: 6465
version: "v1.0.0"

contracts:
  BASE_SEPOLIA:
    RPC: "wss://base-sepolia.g.alchemy.com/v2/_j5REyXi-XySkwLHp790Wvs9kBbxhUba"
    Marketplace:
      address: "0xEdeE6f1E0315d0872CF824A71BC9d5E3Ef5f0b10"
      start_at: 14591456
      query_history: true
      query_interval: 200000

postgres:
  host: "127.0.0.1"
  port: "5432"
  user: ""
  password: ""
  dbname: "marketplace"
  schema: "public"
  max_open_conns: 200
  max_idle_conns: 50
