name: "Marketplace Backend"
mode: "debug"
port: 6465
version: "v1.0.0"

contracts:
  BASE_SEPOLIA:
    RPC: "wss://base-sepolia.g.alchemy.com/v2/_j5REyXi-XySkwLHp790Wvs9kBbxhUba"
    Marketplace:
      address: "0xd7B74EA2242e7e1918fc862997C30C7ef3Bd65C6"
      start_at: 14230579
      query_history: true
      query_interval: 200000
    Application:
      address: "0x704876F802d41c52753Ef708B336d5e572db77A3"
      start_at: 14230342
      query_history: true
      query_interval: 200000

postgre:
  host: "127.0.0.1"
  port: "5432"
  user: ""
  password: ""
  dbname: "marketplace"
  schema: "public"
  max_open_conns: 200
  max_idle_conns: 50
