name: "Marketplace Backend"
mode: "debug"
port: 6465
version: "v1.0.0"

contracts:
  BASE_SEPOLIA:
    RPC: "wss://base-sepolia.g.alchemy.com/v2/_j5REyXi-XySkwLHp790Wvs9kBbxhUba"
    Marketplace:
      address: "0x5606119e87B61228485b761b09AA7A48f7f48980"
      start_at: 14052094
      query_history: true
      query_interval: 200000
    Application:
      address: "0xed867DdA455093e40342F509f817494BC850a598"
      start_at: 14052580
      query_history: true
      query_interval: 200000

postgre:
  host: "127.0.0.1"
  port: "5432"
  user: ""
  password: ""
  dbname: "marketplace"
  schema: "public"
  max_open_conns: 200
  max_idle_conns: 50
